### ISSUE TITLE
Can I use this library to just parse responses (without making requests in the library)?

### ISSUE THREAD

**Issue by sztomi** [jwodder/pypi-simple#1]
I'm working on a simplistic async pypi client that needs to use the simple/legacy api. If I could perform the requests in my async code and pass the responses for parsing by pypi-simple I could use this library instead of implementing my own solution. Is this possible/supported?

**Comment by sztomi** [comment]
Looks like I should be able to call this directly, right? https://github.com/jwodder/pypi-simple/blob/master/pypi_simple.py#L180

**Comment by jwodder** [comment]
Yes, `parse_project_page()` can be called directly to parse a project page's HTML.  I would have made that function public (i.e., mentioned it in the README), but I didn't think anyone was interested in it!
