### ISSUE TITLE
Consider adding ability to provide HTTP timeout params?

### ISSUE THREAD

**Issue by tedpearson** [jwodder/pypi-simple#3]
Example usage: your users are accessing a private pypi repository behind a VPN. When the VPN is not connected, it would be nice to fail fast and print an error, rather than wait indefinitely trying to connect.

Workaround: before calling any pypi-simple methods, first manually issue a requests.get() with timeout to the pypi repository.

**Comment by jwodder** [comment]
`timeout` parameters have been added to the new methods in v0.7.0, out now.

**Comment by tedpearson** [comment]
Thank you very much, works great! 👍
