### ISSUE TITLE
pypi_simple doesn't support option for the latest available release

### ISSUE THREAD

**Issue by matinats** [jwodder/pypi-simple#4]
I would like to be able to get the latest available release in PyPI.
My env is:
$ python3 --version
Python 3.6.8

$ pip3 --version
pip 20.2.4 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

$ pip3 list pypi-simple -V
Package        Version
beautifulsoup4 4.9.3
certifi        2020.11.8
chardet        3.0.4
idna           2.10
packaging      20.4
pip            20.2.4
pyparsing      2.4.7
pypi-simple    0.7.0
requests       2.25.0
setuptools     39.2.0
six            1.15.0
soupsieve      2.0.1
urllib3        1.26.2

My code is:
`from pypi_simple import PyPISimple

pypi_client = PyPISimple(endpoint = 'https://pypi.org/simple/')
requests_page = pypi_client.get_project_page('requests')
pypi_pkg = requests_page.packages[0]
print("The PYPI pkg is: {}".format(pypi_pkg))
`

Is there an easy way to return the latest available release?
Would you be interested in supporting that option?
I see that the latest available from https://pypi.org/project/requests/ it is 2.25.0.

**Comment by jwodder** [comment]
Getting the highest version is easy enough, as shown below, but I feel that this operation is more of a "post-API" step that doesn't really belong in the package, so I'm not interested in adding the operation to the library.

You can get the version string for the highest\* release with the following code (untested, not sure how it works when there are prereleases involved):

\* Note that this returns the *highest* version, not the *latest* version, which is different if the project is releasing versions out of order.  The Simple API doesn't return the information needed to determine the latest version.

```python
from packaging.version import parse
from pypi_simple import PyPISimple

pypi_client = PyPISimple()
requests_page = pypi_client.get_project_page('requests')
versions = [pkg.version for pkg in requests_page.packages if pkg.version is not None]
print(max(versions, key=parse))
```

If you want a `DistributionPackage` for the latest version, you can filter `requests_page.packages` by the highest version as found above, but then it'll be up to you to determine what asset best fits your needs.

**Comment by matinats** [comment]
I understand your point about the highest version instead of latest, that's true.
Thank you very much for your instant support!
