### ISSUE TITLE
Add upload time to package info

### ISSUE THREAD

**Issue by richaagarwal** [jwodder/pypi-simple#5]
It looks like there's no upload time currently provided in a `DistributionPackage` (https://pypi-simple.readthedocs.io/en/stable/high-level-api.html#pypi_simple.DistributionPackage)

Are there plans to add this?  I know that the `releases` endpoint in the PyPI JSON API may be removed in the future (according to https://warehouse.pypa.io/api-reference/json.html, and discussion in https://github.com/pypi/warehouse/pull/11775), so it would be great to have the data currently available at that endpoint (as `upload_time`) available via this API.

**Comment by jwodder** [comment]
At the moment, upload time is only provided by the JSON API, not the Simple API, which is the only API that this package supports.  (Note: When I say "the JSON API", I mean the one documented at <https://warehouse.pypa.io/api-reference/json.html>, not to be confused with the JSON representation of the Simple API.)

However, [there is a proposal to add this information to the Simple API](https://peps.python.org/pep-0700/) (but only to its JSON representation); should that get accepted & implemented in Warehouse, I will add support for it to this package.

**Comment by jwodder** [comment]
PEP 700 has been accepted, and I've just released pypi-simple v1.1.0, which adds the `upload_time` field to `DistributionPackage`.  However, Warehouse has yet to provide this field for any packages; see https://github.com/pypi/warehouse/pull/12727 for progress on that.
